# Generated by Django 5.1.15 on 2026-09-11 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='auth_provider',
            field=models.CharField(default='LOCAL', help_text='Authentication provider (LOCAL, GOOGLE)', max_length=32),
        ),
        migrations.AddField(
            model_name='user',
            name='google_id',
            field=models.CharField(blank=True, db_index=True, help_text='Google OAuth subject identifier (sub)', max_length=255, null=True, unique=True),
        ),
    ]
