# Generated by Django 5.1.15 on 2026-09-16 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_user_auth_provider_user_google_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='year',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Academic year of study (1-4)', null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('STUDENT', 'Student'), ('FACULTY', 'Faculty'), ('MENTOR', 'Mentor / Faculty'), ('ADMIN', 'Institutional Administrator')], db_index=True, default='STUDENT', max_length=16),
        ),
    ]
