# Generated by Django 5.1.15 on 2026-09-16 13:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_user_year_alter_user_role'),
        ('catalogue', '0006_course_category_course_learning_objectives_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='verification_status',
            field=models.CharField(choices=[('PENDING_EMAIL_VERIFICATION', 'Pending Email Verification'), ('VERIFIED', 'Verified / Active'), ('BLOCKED', 'Blocked')], db_index=True, default='VERIFIED', help_text='Institutional email verification status', max_length=32),
        ),
        migrations.CreateModel(
            name='ApprovedStudentDirectory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('register_number', models.CharField(db_index=True, help_text='Official institutional register / roll number', max_length=32, unique=True)),
                ('email', models.EmailField(db_index=True, help_text='Official institutional student email', max_length=254, unique=True)),
                ('full_name', models.CharField(blank=True, max_length=150)),
                ('year', models.PositiveSmallIntegerField(blank=True, help_text='Year of study (1-4)', null=True)),
                ('is_active_student', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_students', to='catalogue.department')),
            ],
            options={
                'verbose_name': 'Approved Student Directory Entry',
                'verbose_name_plural': 'Approved Student Directory',
                'ordering': ['register_number'],
            },
        ),
        migrations.CreateModel(
            name='EmailVerificationOTP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(db_index=True, max_length=254)),
                ('otp_hash', models.CharField(help_text='Cryptographically salted hash of OTP (PBKDF2)', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(db_index=True)),
                ('attempts_count', models.PositiveIntegerField(default=0, help_text='Number of failed attempts with this OTP')),
                ('max_attempts', models.PositiveIntegerField(default=5)),
                ('resend_count', models.PositiveIntegerField(default=0)),
                ('last_resend_at', models.DateTimeField(auto_now_add=True)),
                ('is_used', models.BooleanField(default=False)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='email_otps', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
