# Generated by Django 5.1.15 on 2026-09-11 08:53

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('certificates', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('recipient_email', models.EmailField(max_length=254)),
                ('subject', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('PENDING', 'Pending Dispatch'), ('SENT', 'Sent Successfully'), ('FAILED', 'Failed to Deliver'), ('PENDING_RETRY', 'Pending Retry')], db_index=True, default='PENDING', max_length=16)),
                ('idempotency_key', models.CharField(db_index=True, help_text='Prevents duplicate email deliveries for the same certificate', max_length=128, unique=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('certificate', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='email_logs', to='certificates.certificate')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
