# Generated by Django 5.1.15 on 2026-09-11 08:53

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalogue', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssessmentAttempt',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('IN_PROGRESS', 'In Progress'), ('SUBMITTED', 'Submitted by Student'), ('EXPIRED', 'Expired (Auto-submitted by Server)'), ('EVALUATED', 'Evaluated'), ('CANCELLED', 'Cancelled')], default='IN_PROGRESS', max_length=16)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('server_deadline', models.DateTimeField(help_text='Server-authoritative timer deadline')),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('score', models.FloatField(default=0.0)),
                ('percentage', models.FloatField(default=0.0)),
                ('passed', models.BooleanField(default=False)),
                ('topic_breakdown', models.JSONField(blank=True, default=dict, help_text="Topic mastery percentages e.g. {'python_basics': 80.0}")),
                ('review_status', models.CharField(choices=[('NOT_REQUIRED', 'Not Required / Normal Risk'), ('PENDING_REVIEW', 'Flagged — Pending Mentor Review'), ('VALID', 'Mentor Verified: Valid Attempt'), ('WARNING', 'Mentor Verified: Warning Issued'), ('INVALID', 'Mentor Verified: Invalidated for Misconduct')], default='NOT_REQUIRED', max_length=20)),
                ('is_demo', models.BooleanField(db_index=True, default=False)),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('topic_tag', models.CharField(db_index=True, help_text='Corresponds with Module topic_tag for skill-gap diagnosis', max_length=64)),
                ('question_type', models.CharField(choices=[('MCQ_SINGLE', 'Single Choice MCQ'), ('MCQ_MULTIPLE', 'Multiple Choice MCQ'), ('TRUE_FALSE', 'True / False')], default='MCQ_SINGLE', max_length=16)),
                ('difficulty', models.CharField(choices=[('EASY', 'Easy'), ('MEDIUM', 'Medium'), ('HARD', 'Hard')], default='MEDIUM', max_length=16)),
                ('marks', models.PositiveIntegerField(default=1)),
                ('explanation', models.TextField(blank=True, help_text='Pedagogical explanation shown post-submission')),
                ('order', models.PositiveIntegerField(default=1)),
            ],
            options={
                'ordering': ['assessment', 'order'],
            },
        ),
        migrations.CreateModel(
            name='QuestionOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=255)),
                ('is_correct', models.BooleanField(default=False)),
                ('order', models.PositiveIntegerField(default=1)),
            ],
            options={
                'ordering': ['question', 'order'],
            },
        ),
        migrations.CreateModel(
            name='StudentAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_correct', models.BooleanField(default=False)),
                ('marks_obtained', models.FloatField(default=0.0)),
                ('answered_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Assessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('assessment_type', models.CharField(choices=[('PRE_ASSESSMENT', 'Diagnostic Pre-Assessment (Skill Gap Analysis)'), ('FINAL_ASSESSMENT', 'Final Certification Assessment')], default='FINAL_ASSESSMENT', max_length=32)),
                ('version', models.PositiveIntegerField(default=1, help_text='Immutable assessment version for reproducibility')),
                ('duration_minutes', models.PositiveIntegerField(default=30)),
                ('pass_percentage', models.FloatField(default=70.0)),
                ('max_attempts', models.PositiveIntegerField(default=3)),
                ('randomize_questions', models.BooleanField(default=True)),
                ('randomize_options', models.BooleanField(default=True)),
                ('is_published', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assessments', to='catalogue.course')),
            ],
            options={
                'ordering': ['course', '-version'],
            },
        ),
    ]
