# Generated by Django 5.1.15 on 2026-09-11 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='assessment',
            name='auto_terminate_on_limit',
            field=models.BooleanField(default=True, help_text='Automatically terminate attempt when any warning limit is breached'),
        ),
        migrations.AddField(
            model_name='assessment',
            name='camera_required',
            field=models.BooleanField(default=True, help_text='Requires continuous camera stream'),
        ),
        migrations.AddField(
            model_name='assessment',
            name='face_detection_enabled',
            field=models.BooleanField(default=True, help_text='Enables computer-vision face-count detection'),
        ),
        migrations.AddField(
            model_name='assessment',
            name='fullscreen_required',
            field=models.BooleanField(default=True, help_text='Requires browser fullscreen enforcement'),
        ),
        migrations.AddField(
            model_name='assessment',
            name='max_camera_warnings',
            field=models.PositiveIntegerField(default=2, help_text='Maximum allowed camera disconnect warnings before termination'),
        ),
        migrations.AddField(
            model_name='assessment',
            name='max_fullscreen_warnings',
            field=models.PositiveIntegerField(default=2, help_text='Maximum allowed fullscreen exit warnings'),
        ),
        migrations.AddField(
            model_name='assessment',
            name='max_multiple_face_warnings',
            field=models.PositiveIntegerField(default=2, help_text='Maximum allowed multiple-face warnings before termination'),
        ),
        migrations.AddField(
            model_name='assessment',
            name='max_screen_share_warnings',
            field=models.PositiveIntegerField(default=2, help_text='Maximum allowed screen-share interruption warnings'),
        ),
        migrations.AddField(
            model_name='assessment',
            name='max_tab_switch_warnings',
            field=models.PositiveIntegerField(default=2, help_text='Maximum allowed tab switch / blur warnings'),
        ),
        migrations.AddField(
            model_name='assessment',
            name='multiple_faces_threshold_seconds',
            field=models.FloatField(default=2.0, help_text='Debounce threshold seconds for multiple face detection'),
        ),
        migrations.AddField(
            model_name='assessment',
            name='screen_share_required',
            field=models.BooleanField(default=True, help_text='Requires continuous active screen sharing'),
        ),
        migrations.AddField(
            model_name='assessmentattempt',
            name='camera_warning_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='assessmentattempt',
            name='fullscreen_warning_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='assessmentattempt',
            name='multiple_face_warning_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='assessmentattempt',
            name='screen_share_warning_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='assessmentattempt',
            name='tab_switch_warning_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='assessmentattempt',
            name='terminated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='assessmentattempt',
            name='termination_reason',
            field=models.TextField(blank=True, help_text='Authoritative reason if attempt was terminated for violation', null=True),
        ),
        migrations.AlterField(
            model_name='assessmentattempt',
            name='status',
            field=models.CharField(choices=[('READY', 'Ready to Begin'), ('IN_PROGRESS', 'In Progress'), ('WARNING', 'Security Warning Active'), ('SUBMITTED', 'Submitted by Student'), ('EXPIRED', 'Expired (Auto-submitted by Server)'), ('EVALUATED', 'Evaluated'), ('PASSED', 'Passed'), ('FAILED', 'Failed'), ('FLAGGED', 'Flagged for Proctoring Review'), ('TERMINATED_SECURITY_VIOLATION', 'Terminated: Security Violation'), ('CANCELLED', 'Cancelled')], db_index=True, default='IN_PROGRESS', max_length=32),
        ),
    ]
