# Generated by Django 5.1.15 on 2026-09-12 07:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0003_assessment_auto_terminate_on_limit_and_more'),
        ('catalogue', '0005_course_blueprint_course_learning_goal_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='assessment',
            name='blueprint',
            field=models.JSONField(blank=True, default=dict, help_text='Question count, difficulty, topic distribution blueprint'),
        ),
        migrations.AddField(
            model_name='assessment',
            name='is_ai_generated',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='assessmentattempt',
            name='question_option_orders',
            field=models.JSONField(blank=True, default=dict, help_text='Randomized option order map per question'),
        ),
        migrations.AddField(
            model_name='assessmentattempt',
            name='selected_question_ids',
            field=models.JSONField(blank=True, default=list, help_text='Ordered question IDs sampled for this specific attempt'),
        ),
        migrations.AddField(
            model_name='question',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='question_bank', to='catalogue.course'),
        ),
        migrations.AddField(
            model_name='question',
            name='is_bank_question',
            field=models.BooleanField(db_index=True, default=False, help_text='Member of the Course AI Question Bank pool'),
        ),
        migrations.AddField(
            model_name='question',
            name='quality_score',
            field=models.FloatField(default=1.0, help_text='AI quality assurance score (0.0 - 1.0)'),
        ),
        migrations.AddField(
            model_name='question',
            name='semantic_hash',
            field=models.CharField(blank=True, db_index=True, help_text='Normalized token hash for duplicate detection', max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='assessment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='assessments.assessment'),
        ),
    ]
