# Generated by Django 5.1.15 on 2026-09-15 06:08

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0004_assessment_blueprint_assessment_is_ai_generated_and_more'),
        ('learning', '0003_videoprogress_completion_mode_reportedvideoissue'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'Active'), ('QUESTION_REQUIRES_REVIEW', 'Requires Review')], db_index=True, default='ACTIVE', help_text='Integrity status of question content and answer key', max_length=32),
        ),
        migrations.AlterField(
            model_name='assessmentattempt',
            name='enrollment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attempts', to='learning.enrollment'),
        ),
        migrations.AlterField(
            model_name='assessmentattempt',
            name='question_option_orders',
            field=models.JSONField(blank=True, default=dict, help_text='Mapping of question_id -> randomized option_ids order'),
        ),
        migrations.AlterField(
            model_name='assessmentattempt',
            name='review_status',
            field=models.CharField(choices=[('CLEAN', 'Clean'), ('WARNING', 'Warning Flagged'), ('INVALID', 'Invalidated')], default='CLEAN', max_length=16),
        ),
        migrations.AlterField(
            model_name='assessmentattempt',
            name='selected_question_ids',
            field=models.JSONField(blank=True, default=list, help_text='Specific Question IDs chosen from the pool for this attempt'),
        ),
        migrations.AlterField(
            model_name='assessmentattempt',
            name='server_deadline',
            field=models.DateTimeField(help_text='Server-enforced deadline beyond which submissions are auto-closed'),
        ),
        migrations.AlterField(
            model_name='assessmentattempt',
            name='started_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='assessmentattempt',
            name='status',
            field=models.CharField(choices=[('READY', 'Ready to Begin'), ('IN_PROGRESS', 'In Progress'), ('WARNING', 'Security Warning Active'), ('SUBMITTED', 'Submitted by Student'), ('EXPIRED', 'Expired (Auto-submitted by Server)'), ('EVALUATED', 'Evaluated'), ('PASSED', 'Passed'), ('FAILED', 'Failed'), ('TERMINATED_SECURITY_VIOLATION', 'Terminated Due to Critical Security Violation')], default='READY', max_length=32),
        ),
        migrations.AlterField(
            model_name='assessmentattempt',
            name='termination_reason',
            field=models.TextField(blank=True, help_text='Reason recorded if auto-terminated by AssessmentSecurityEngine', null=True),
        ),
        migrations.AlterField(
            model_name='assessmentattempt',
            name='topic_breakdown',
            field=models.JSONField(blank=True, default=dict, help_text='Diagnostic topic percentage scores for skill gaps'),
        ),
        migrations.AlterField(
            model_name='question',
            name='difficulty',
            field=models.CharField(choices=[('EASY', 'Easy'), ('MEDIUM', 'Medium'), ('HARD', 'Hard')], default='EASY', max_length=16),
        ),
    ]
