# Generated by Django 5.1.15 on 2026-09-18 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0005_question_status_alter_assessmentattempt_enrollment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='approval_status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('PENDING_REVIEW', 'Pending Review'), ('APPROVED', 'Approved')], db_index=True, default='APPROVED', max_length=32),
        ),
        migrations.AddField(
            model_name='question',
            name='constraints',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='question',
            name='hidden_test_cases',
            field=models.JSONField(blank=True, default=list, help_text="Exactly 4 hidden test cases: [{'input': '...', 'output': '...'}]"),
        ),
        migrations.AddField(
            model_name='question',
            name='input_format',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='question',
            name='output_format',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='question',
            name='problem_statement',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='question',
            name='programming_language',
            field=models.CharField(blank=True, choices=[('c', 'C'), ('cpp', 'C++'), ('java', 'Java'), ('python', 'Python')], default='', help_text='Required programming language for this coding problem', max_length=16),
        ),
        migrations.AddField(
            model_name='question',
            name='reference_solution',
            field=models.TextField(blank=True, default='', help_text='Trusted reference solution for automated validation'),
        ),
        migrations.AddField(
            model_name='question',
            name='sample_test_cases',
            field=models.JSONField(blank=True, default=list, help_text="Exactly 2 visible test cases: [{'input': '...', 'output': '...'}]"),
        ),
        migrations.AddField(
            model_name='question',
            name='title',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='studentanswer',
            name='code_execution_details',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='studentanswer',
            name='code_language',
            field=models.CharField(blank=True, default='', max_length=16),
        ),
        migrations.AddField(
            model_name='studentanswer',
            name='submitted_code',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='studentanswer',
            name='test_cases_passed',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='studentanswer',
            name='total_test_cases',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='question',
            name='question_type',
            field=models.CharField(choices=[('MCQ_SINGLE', 'Single Choice MCQ'), ('MCQ_MULTIPLE', 'Multiple Choice MCQ'), ('TRUE_FALSE', 'True / False'), ('CODING', 'Programming Coding Question')], default='MCQ_SINGLE', max_length=16),
        ),
    ]
