# Generated by Django 5.1.15 on 2026-09-12 05:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0003_course_status_lesson_description_and_more'),
        ('learning', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moduleprogress',
            name='is_completed',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.CreateModel(
            name='MaterialProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('OPENED', 'Opened'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed')], default='OPENED', max_length=32)),
                ('is_completed', models.BooleanField(db_index=True, default=False)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('enrollment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='material_progress', to='learning.enrollment')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_progress', to='catalogue.studymaterial')),
            ],
            options={
                'unique_together': {('enrollment', 'material')},
            },
        ),
        migrations.CreateModel(
            name='PracticeProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attempt_count', models.PositiveIntegerField(default=0)),
                ('best_score', models.FloatField(default=0.0)),
                ('is_completed', models.BooleanField(db_index=True, default=False)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('enrollment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='practice_progress', to='learning.enrollment')),
                ('practice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_progress', to='catalogue.practicetask')),
            ],
            options={
                'unique_together': {('enrollment', 'practice')},
            },
        ),
        migrations.CreateModel(
            name='VideoProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('watched_seconds', models.PositiveIntegerField(default=0)),
                ('watch_percentage', models.FloatField(default=0.0)),
                ('last_position', models.PositiveIntegerField(default=0)),
                ('is_completed', models.BooleanField(db_index=True, default=False)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('enrollment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='video_progress', to='learning.enrollment')),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_progress', to='catalogue.videoresource')),
            ],
            options={
                'unique_together': {('enrollment', 'video')},
            },
        ),
    ]
