# Generated by Django 5.1.15 on 2026-09-12 06:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0004_studymaterial_reviewed_at_studymaterial_reviewed_by_and_more'),
        ('learning', '0002_alter_moduleprogress_is_completed_materialprogress_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='videoprogress',
            name='completion_mode',
            field=models.CharField(choices=[('WATCH_THRESHOLD', 'Watch Threshold Achieved'), ('VIDEO_STARTED_MANUAL', 'Started and Confirmed by Student')], default='WATCH_THRESHOLD', max_length=32),
        ),
        migrations.CreateModel(
            name='ReportedVideoIssue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issue_type', models.CharField(choices=[('UNAVAILABLE', 'Video is unavailable or deleted on YouTube'), ('EMBEDDING_DISABLED', 'Video playback on external sites has been disabled by owner'), ('PRIVATE', 'Video is marked private or restricted'), ('BROKEN_CONTENT', 'Content or audio is distorted / broken'), ('TOPIC_MISMATCH', 'Video does not teach the stated topic'), ('OTHER', 'Other Technical Issue')], default='UNAVAILABLE', max_length=32)),
                ('notes', models.TextField(blank=True, help_text='Student description of problem')),
                ('status', models.CharField(choices=[('OPEN', 'Open for Faculty/Admin Review'), ('RESOLVED', 'Resolved / Video Replaced'), ('DISMISSED', 'Dismissed / Tested Working')], default='OPEN', max_length=32)),
                ('replacement_video_id', models.CharField(blank=True, help_text='New YouTube ID assigned by Admin', max_length=64, null=True)),
                ('reported_at', models.DateTimeField(auto_now_add=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_video_issues', to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reported_video_issues', to=settings.AUTH_USER_MODEL)),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reported_issues', to='catalogue.videoresource')),
            ],
            options={
                'ordering': ['-reported_at'],
            },
        ),
    ]
