# Generated by Django 5.1.15 on 2026-09-11 08:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('assessments', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MentorReviewRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('verdict', models.CharField(choices=[('VALID', 'Valid (Clear to issue certificate if passed)'), ('WARNING', 'Warning Issued (Result retained, warning recorded)'), ('INVALID', 'Invalidated (Misconduct confirmed by mentor)'), ('NEEDS_MORE_REVIEW', 'Needs Administrative Escalation')], max_length=24)),
                ('notes', models.TextField(help_text='Detailed audit notes explaining reviewer determination')),
                ('reviewed_at', models.DateTimeField(auto_now_add=True)),
                ('attempt', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='mentor_review', to='assessments.assessmentattempt')),
                ('reviewer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proctoring_reviews', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ProctoringEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('TAB_SWITCH', 'Page Visibility / Tab Switched Away'), ('FULLSCREEN_EXIT', 'Fullscreen Lock Exited'), ('CAMERA_DISCONNECTED', 'Video Track Stopped / Camera Inaccessible'), ('SCREEN_SHARE_STOPPED', 'Screen Sharing Session Disconnected'), ('SUSPICIOUS_KEY', 'Restricted Shortcut / Hotkey Detected'), ('WINDOW_BLUR', 'Window Lost Focus')], max_length=32)),
                ('severity', models.CharField(choices=[('INFO', 'Informational Notice'), ('LOW', 'Minor Warning'), ('MEDIUM', 'Moderate Suspicious Signal'), ('HIGH', 'Major Integrity Signal'), ('CRITICAL', 'Severe Signal')], default='MEDIUM', max_length=16)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('details', models.JSONField(blank=True, default=dict)),
                ('attempt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proctoring_events', to='assessments.assessmentattempt')),
            ],
            options={
                'ordering': ['attempt', 'timestamp'],
            },
        ),
        migrations.CreateModel(
            name='RiskScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numerical_score', models.FloatField(default=0.0, help_text='Calculated risk points (0 to 100)')),
                ('tier', models.CharField(choices=[('NORMAL', 'Normal Activity'), ('LOW', 'Low Risk'), ('MEDIUM', 'Moderate Risk'), ('HIGH', 'High Risk — Review Recommended'), ('CRITICAL', 'Critical Risk — Review Required')], default='NORMAL', max_length=16)),
                ('event_count', models.PositiveIntegerField(default=0)),
                ('evaluated_at', models.DateTimeField(auto_now=True)),
                ('attempt', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='risk_assessment', to='assessments.assessmentattempt')),
            ],
        ),
    ]
