# Generated by Django 5.1.15 on 2026-09-11 14:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proctoring', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='proctoringevent',
            name='action_taken',
            field=models.CharField(default='NONE', help_text='Action taken e.g. WARNING_ISSUED, AUTO_TERMINATE, RECORDED', max_length=64),
        ),
        migrations.AddField(
            model_name='proctoringevent',
            name='current_warning_count',
            field=models.PositiveIntegerField(default=0, help_text='Warning count for this specific violation type at event time'),
        ),
        migrations.AddField(
            model_name='proctoringevent',
            name='student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='proctoring_events', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='proctoringevent',
            name='event_type',
            field=models.CharField(choices=[('TAB_SWITCH', 'Page Visibility / Tab Switched Away'), ('TAB_RESTORED', 'Tab Returned / Focus Restored'), ('FULLSCREEN_EXIT', 'Fullscreen Lock Exited'), ('FULLSCREEN_RESTORED', 'Fullscreen Lock Re-entered'), ('CAMERA_UNAVAILABLE', 'Camera Feed Lost / Inaccessible'), ('CAMERA_RECONNECTED', 'Camera Feed Reconnected'), ('CAMERA_DISCONNECTED', 'Video Track Stopped / Camera Inaccessible'), ('MULTIPLE_FACES_DETECTED', 'Multiple Faces Detected in View'), ('FACE_NOT_DETECTED', 'No Face Detected in View'), ('ONE_FACE_DETECTED', 'Single Verified Face in View (Normal)'), ('SCREEN_SHARE_STOPPED', 'Screen Sharing Session Disconnected'), ('SCREEN_SHARE_RESUMED', 'Screen Sharing Resumed'), ('SUSPICIOUS_KEY', 'Restricted Shortcut / Hotkey Detected'), ('WINDOW_BLUR', 'Window Lost Focus'), ('SECURITY_TERMINATION', 'Automated Session Termination for Violations')], db_index=True, max_length=32),
        ),
    ]
