# Generated by Django 5.1.15 on 2026-09-18 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proctoring', '0002_proctoringevent_action_taken_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proctoringevent',
            name='event_type',
            field=models.CharField(choices=[('TAB_SWITCH', 'Page Visibility / Tab Switched Away'), ('TAB_RESTORED', 'Tab Returned / Focus Restored'), ('FULLSCREEN_EXIT', 'Fullscreen Lock Exited'), ('FULLSCREEN_RESTORED', 'Fullscreen Lock Re-entered'), ('CAMERA_UNAVAILABLE', 'Camera Feed Lost / Inaccessible'), ('CAMERA_RECONNECTED', 'Camera Feed Reconnected'), ('CAMERA_DISCONNECTED', 'Video Track Stopped / Camera Inaccessible'), ('CAMERA_COVERED_BLANK', 'Camera Covered or Blank Screen Detected'), ('MULTIPLE_FACES_DETECTED', 'Multiple Faces Detected in View'), ('FACE_NOT_DETECTED', 'No Face Detected in View'), ('ONE_FACE_DETECTED', 'Single Verified Face in View (Normal)'), ('MOBILE_PHONE_DETECTED', 'Mobile Phone / Unauthorized Device Detected'), ('AI_ASSISTANCE_DETECTED', 'AI Assistant / External Help Tool Detected'), ('SCREEN_SHARE_STOPPED', 'Screen Sharing Session Disconnected'), ('SCREEN_SHARE_RESUMED', 'Screen Sharing Resumed'), ('SUSPICIOUS_KEY', 'Restricted Shortcut / Hotkey Detected'), ('WINDOW_BLUR', 'Window Lost Focus'), ('SECURITY_TERMINATION', 'Automated Session Termination for Violations')], db_index=True, max_length=32),
        ),
    ]
