# Generated by Django 5.1.15 on 2026-09-11 08:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_type', models.CharField(choices=[('FXEC_OFFICIAL', 'FXEC Official Website / Document'), ('NPTEL_OFFICIAL', 'NPTEL Official Public Resource'), ('EXTERNAL_PUBLIC', 'External Public Learning Reference'), ('ADMIN_CREATED', 'Authorized Mentor / Admin Input')], default='FXEC_OFFICIAL', max_length=32)),
                ('source_url', models.URLField(blank=True, help_text='Canonical URL where fact was retrieved', null=True)),
                ('source_title', models.CharField(blank=True, help_text='Authoritative title of webpage/document', max_length=255, null=True)),
                ('source_accessed_at', models.DateTimeField(blank=True, help_text='Timestamp when source was accessed', null=True)),
                ('last_verified_at', models.DateTimeField(blank=True, help_text='Timestamp of last provenance verification', null=True)),
                ('content_status', models.CharField(choices=[('DRAFT', 'Draft'), ('PENDING_ADMIN_INPUT', 'Pending Institutional Verification'), ('PUBLISHED', 'Published & Verified')], default='PUBLISHED', max_length=32)),
                ('code', models.CharField(max_length=16, unique=True)),
                ('name', models.CharField(max_length=128)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='SkillCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_type', models.CharField(choices=[('FXEC_OFFICIAL', 'FXEC Official Website / Document'), ('NPTEL_OFFICIAL', 'NPTEL Official Public Resource'), ('EXTERNAL_PUBLIC', 'External Public Learning Reference'), ('ADMIN_CREATED', 'Authorized Mentor / Admin Input')], default='FXEC_OFFICIAL', max_length=32)),
                ('source_url', models.URLField(blank=True, help_text='Canonical URL where fact was retrieved', null=True)),
                ('source_title', models.CharField(blank=True, help_text='Authoritative title of webpage/document', max_length=255, null=True)),
                ('source_accessed_at', models.DateTimeField(blank=True, help_text='Timestamp when source was accessed', null=True)),
                ('last_verified_at', models.DateTimeField(blank=True, help_text='Timestamp of last provenance verification', null=True)),
                ('content_status', models.CharField(choices=[('DRAFT', 'Draft'), ('PENDING_ADMIN_INPUT', 'Pending Institutional Verification'), ('PUBLISHED', 'Published & Verified')], default='PUBLISHED', max_length=32)),
                ('name', models.CharField(max_length=64, unique=True)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Skill Categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_type', models.CharField(choices=[('FXEC_OFFICIAL', 'FXEC Official Website / Document'), ('NPTEL_OFFICIAL', 'NPTEL Official Public Resource'), ('EXTERNAL_PUBLIC', 'External Public Learning Reference'), ('ADMIN_CREATED', 'Authorized Mentor / Admin Input')], default='FXEC_OFFICIAL', max_length=32)),
                ('source_url', models.URLField(blank=True, help_text='Canonical URL where fact was retrieved', null=True)),
                ('source_title', models.CharField(blank=True, help_text='Authoritative title of webpage/document', max_length=255, null=True)),
                ('source_accessed_at', models.DateTimeField(blank=True, help_text='Timestamp when source was accessed', null=True)),
                ('last_verified_at', models.DateTimeField(blank=True, help_text='Timestamp of last provenance verification', null=True)),
                ('content_status', models.CharField(choices=[('DRAFT', 'Draft'), ('PENDING_ADMIN_INPUT', 'Pending Institutional Verification'), ('PUBLISHED', 'Published & Verified')], default='PUBLISHED', max_length=32)),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('instructor_name', models.CharField(default='FXEC Faculty Team', max_length=128)),
                ('description', models.TextField()),
                ('outcomes', models.JSONField(blank=True, default=list)),
                ('thumbnail_url', models.URLField(blank=True, null=True)),
                ('estimated_hours', models.PositiveIntegerField(default=10)),
                ('is_published', models.BooleanField(db_index=True, default=True)),
                ('is_demo', models.BooleanField(db_index=True, default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='courses', to='catalogue.department')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_type', models.CharField(choices=[('FXEC_OFFICIAL', 'FXEC Official Website / Document'), ('NPTEL_OFFICIAL', 'NPTEL Official Public Resource'), ('EXTERNAL_PUBLIC', 'External Public Learning Reference'), ('ADMIN_CREATED', 'Authorized Mentor / Admin Input')], default='FXEC_OFFICIAL', max_length=32)),
                ('source_url', models.URLField(blank=True, help_text='Canonical URL where fact was retrieved', null=True)),
                ('source_title', models.CharField(blank=True, help_text='Authoritative title of webpage/document', max_length=255, null=True)),
                ('source_accessed_at', models.DateTimeField(blank=True, help_text='Timestamp when source was accessed', null=True)),
                ('last_verified_at', models.DateTimeField(blank=True, help_text='Timestamp of last provenance verification', null=True)),
                ('content_status', models.CharField(choices=[('DRAFT', 'Draft'), ('PENDING_ADMIN_INPUT', 'Pending Institutional Verification'), ('PUBLISHED', 'Published & Verified')], default='PUBLISHED', max_length=32)),
                ('order', models.PositiveIntegerField(default=1)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('topic_tag', models.CharField(db_index=True, help_text='Topic identifier for skill-gap diagnosis mapping', max_length=64)),
                ('duration_minutes', models.PositiveIntegerField(default=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modules', to='catalogue.course')),
            ],
            options={
                'ordering': ['course', 'order'],
                'unique_together': {('course', 'order')},
            },
        ),
        migrations.CreateModel(
            name='LearningResource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_type', models.CharField(choices=[('FXEC_OFFICIAL', 'FXEC Official Website / Document'), ('NPTEL_OFFICIAL', 'NPTEL Official Public Resource'), ('EXTERNAL_PUBLIC', 'External Public Learning Reference'), ('ADMIN_CREATED', 'Authorized Mentor / Admin Input')], default='FXEC_OFFICIAL', max_length=32)),
                ('source_url', models.URLField(blank=True, help_text='Canonical URL where fact was retrieved', null=True)),
                ('source_title', models.CharField(blank=True, help_text='Authoritative title of webpage/document', max_length=255, null=True)),
                ('source_accessed_at', models.DateTimeField(blank=True, help_text='Timestamp when source was accessed', null=True)),
                ('last_verified_at', models.DateTimeField(blank=True, help_text='Timestamp of last provenance verification', null=True)),
                ('content_status', models.CharField(choices=[('DRAFT', 'Draft'), ('PENDING_ADMIN_INPUT', 'Pending Institutional Verification'), ('PUBLISHED', 'Published & Verified')], default='PUBLISHED', max_length=32)),
                ('title', models.CharField(max_length=200)),
                ('resource_type', models.CharField(choices=[('VIDEO_LINK', 'Video Lecture (External Link / Embed)'), ('DOCUMENT_LINK', 'Reference Document / Syllabus (PDF / Link)'), ('INTERACTIVE_LAB', 'Hands-on Practice / Lab Exercise'), ('READING_MATERIAL', 'Curated Notes / Study Guide')], default='VIDEO_LINK', max_length=32)),
                ('content_url', models.URLField(blank=True, help_text='Lawful URL to external public or institutional material', null=True)),
                ('text_content', models.TextField(blank=True, help_text='Explanatory notes or guide')),
                ('order', models.PositiveIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resources', to='catalogue.module')),
            ],
            options={
                'ordering': ['module', 'order'],
            },
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_type', models.CharField(choices=[('FXEC_OFFICIAL', 'FXEC Official Website / Document'), ('NPTEL_OFFICIAL', 'NPTEL Official Public Resource'), ('EXTERNAL_PUBLIC', 'External Public Learning Reference'), ('ADMIN_CREATED', 'Authorized Mentor / Admin Input')], default='FXEC_OFFICIAL', max_length=32)),
                ('source_url', models.URLField(blank=True, help_text='Canonical URL where fact was retrieved', null=True)),
                ('source_title', models.CharField(blank=True, help_text='Authoritative title of webpage/document', max_length=255, null=True)),
                ('source_accessed_at', models.DateTimeField(blank=True, help_text='Timestamp when source was accessed', null=True)),
                ('last_verified_at', models.DateTimeField(blank=True, help_text='Timestamp of last provenance verification', null=True)),
                ('content_status', models.CharField(choices=[('DRAFT', 'Draft'), ('PENDING_ADMIN_INPUT', 'Pending Institutional Verification'), ('PUBLISHED', 'Published & Verified')], default='PUBLISHED', max_length=32)),
                ('name', models.CharField(max_length=128)),
                ('description', models.TextField(blank=True)),
                ('level', models.CharField(choices=[('BEGINNER', 'Beginner'), ('INTERMEDIATE', 'Intermediate'), ('ADVANCED', 'Advanced')], default='BEGINNER', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='skills', to='catalogue.department')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skills', to='catalogue.skillcategory')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='course',
            name='skill',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='catalogue.skill'),
        ),
    ]
