# Generated by Django 5.1.15 on 2026-09-12 04:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='skillcategory',
            options={'ordering': ['order', 'name'], 'verbose_name_plural': 'Skill Categories'},
        ),
        migrations.AddField(
            model_name='course',
            name='approval_status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('PENDING_REVIEW', 'Pending Review'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('ARCHIVED', 'Archived')], default='APPROVED', max_length=32),
        ),
        migrations.AddField(
            model_name='course',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_approved', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='course',
            name='course_types',
            field=models.JSONField(blank=True, default=list, help_text="e.g. ['CORE_SKILL', 'INTERDISCIPLINARY', 'VALUE_ADDED']"),
        ),
        migrations.AddField(
            model_name='course',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='course',
            name='departments',
            field=models.ManyToManyField(blank=True, related_name='multi_courses', to='catalogue.department'),
        ),
        migrations.AddField(
            model_name='course',
            name='level',
            field=models.CharField(choices=[('BEGINNER', 'Beginner'), ('INTERMEDIATE', 'Intermediate'), ('ADVANCED', 'Advanced'), ('EXPERT', 'Expert')], default='BEGINNER', max_length=16),
        ),
        migrations.AddField(
            model_name='course',
            name='prerequisites',
            field=models.ManyToManyField(blank=True, related_name='follow_up_courses', to='catalogue.course'),
        ),
        migrations.AddField(
            model_name='course',
            name='skills',
            field=models.ManyToManyField(blank=True, related_name='multi_courses', to='catalogue.skill'),
        ),
        migrations.AddField(
            model_name='course',
            name='source_description',
            field=models.TextField(blank=True, help_text='Explanatory context of institutional origin', null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='version',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='department',
            name='approval_status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('PENDING_REVIEW', 'Pending Review'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('ARCHIVED', 'Archived')], default='APPROVED', max_length=32),
        ),
        migrations.AddField(
            model_name='department',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_approved', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='department',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='department',
            name='source_description',
            field=models.TextField(blank=True, help_text='Explanatory context of institutional origin', null=True),
        ),
        migrations.AddField(
            model_name='learningresource',
            name='approval_status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('PENDING_REVIEW', 'Pending Review'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('ARCHIVED', 'Archived')], default='APPROVED', max_length=32),
        ),
        migrations.AddField(
            model_name='learningresource',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_approved', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='learningresource',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='learningresource',
            name='source_description',
            field=models.TextField(blank=True, help_text='Explanatory context of institutional origin', null=True),
        ),
        migrations.AddField(
            model_name='module',
            name='approval_status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('PENDING_REVIEW', 'Pending Review'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('ARCHIVED', 'Archived')], default='APPROVED', max_length=32),
        ),
        migrations.AddField(
            model_name='module',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_approved', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='module',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='module',
            name='source_description',
            field=models.TextField(blank=True, help_text='Explanatory context of institutional origin', null=True),
        ),
        migrations.AddField(
            model_name='skill',
            name='approval_status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('PENDING_REVIEW', 'Pending Review'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('ARCHIVED', 'Archived')], default='APPROVED', max_length=32),
        ),
        migrations.AddField(
            model_name='skill',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_approved', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='skill',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='skill',
            name='departments',
            field=models.ManyToManyField(blank=True, related_name='multi_skills', to='catalogue.department'),
        ),
        migrations.AddField(
            model_name='skill',
            name='estimated_duration',
            field=models.CharField(blank=True, default='4 Weeks', max_length=64),
        ),
        migrations.AddField(
            model_name='skill',
            name='is_cross_department',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='skill',
            name='learning_outcomes',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='skill',
            name='prerequisites',
            field=models.ManyToManyField(blank=True, related_name='dependent_skills', to='catalogue.skill'),
        ),
        migrations.AddField(
            model_name='skill',
            name='skill_type',
            field=models.CharField(choices=[('CORE', 'Core Skill'), ('ELECTIVE', 'Elective Skill'), ('FACULTY_INITIATIVE', 'Faculty Initiative'), ('EMERGING', 'Emerging / Future Skill'), ('PLACEMENT', 'Placement Fit Training'), ('TECHNICAL', 'Technical Skill'), ('NON_TECHNICAL', 'Non-Technical Skill')], default='CORE', max_length=32),
        ),
        migrations.AddField(
            model_name='skill',
            name='source_description',
            field=models.TextField(blank=True, help_text='Explanatory context of institutional origin', null=True),
        ),
        migrations.AddField(
            model_name='skillcategory',
            name='approval_status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('PENDING_REVIEW', 'Pending Review'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('ARCHIVED', 'Archived')], default='APPROVED', max_length=32),
        ),
        migrations.AddField(
            model_name='skillcategory',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_approved', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='skillcategory',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='skillcategory',
            name='order',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='skillcategory',
            name='source_description',
            field=models.TextField(blank=True, help_text='Explanatory context of institutional origin', null=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='content_status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('PENDING_ADMIN_INPUT', 'Pending Institutional Verification'), ('PUBLISHED', 'Published & Verified'), ('UNPUBLISHED', 'Unpublished'), ('ARCHIVED', 'Archived')], default='PUBLISHED', max_length=32),
        ),
        migrations.AlterField(
            model_name='course',
            name='source_type',
            field=models.CharField(choices=[('FXEC_OFFICIAL', 'FXEC Official Website / Document'), ('FACULTY_CREATED', 'Faculty Created'), ('ADMIN_CREATED', 'Authorized Mentor / Admin Input'), ('AI_SUGGESTED', 'AI Suggested'), ('EXTERNAL_REFERENCE', 'External Public Reference'), ('NPTEL_OFFICIAL', 'NPTEL Official Public Resource'), ('EXTERNAL_PUBLIC', 'External Public Learning Reference')], default='FXEC_OFFICIAL', max_length=32),
        ),
        migrations.AlterField(
            model_name='department',
            name='content_status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('PENDING_ADMIN_INPUT', 'Pending Institutional Verification'), ('PUBLISHED', 'Published & Verified'), ('UNPUBLISHED', 'Unpublished'), ('ARCHIVED', 'Archived')], default='PUBLISHED', max_length=32),
        ),
        migrations.AlterField(
            model_name='department',
            name='source_type',
            field=models.CharField(choices=[('FXEC_OFFICIAL', 'FXEC Official Website / Document'), ('FACULTY_CREATED', 'Faculty Created'), ('ADMIN_CREATED', 'Authorized Mentor / Admin Input'), ('AI_SUGGESTED', 'AI Suggested'), ('EXTERNAL_REFERENCE', 'External Public Reference'), ('NPTEL_OFFICIAL', 'NPTEL Official Public Resource'), ('EXTERNAL_PUBLIC', 'External Public Learning Reference')], default='FXEC_OFFICIAL', max_length=32),
        ),
        migrations.AlterField(
            model_name='learningresource',
            name='content_status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('PENDING_ADMIN_INPUT', 'Pending Institutional Verification'), ('PUBLISHED', 'Published & Verified'), ('UNPUBLISHED', 'Unpublished'), ('ARCHIVED', 'Archived')], default='PUBLISHED', max_length=32),
        ),
        migrations.AlterField(
            model_name='learningresource',
            name='source_type',
            field=models.CharField(choices=[('FXEC_OFFICIAL', 'FXEC Official Website / Document'), ('FACULTY_CREATED', 'Faculty Created'), ('ADMIN_CREATED', 'Authorized Mentor / Admin Input'), ('AI_SUGGESTED', 'AI Suggested'), ('EXTERNAL_REFERENCE', 'External Public Reference'), ('NPTEL_OFFICIAL', 'NPTEL Official Public Resource'), ('EXTERNAL_PUBLIC', 'External Public Learning Reference')], default='FXEC_OFFICIAL', max_length=32),
        ),
        migrations.AlterField(
            model_name='module',
            name='content_status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('PENDING_ADMIN_INPUT', 'Pending Institutional Verification'), ('PUBLISHED', 'Published & Verified'), ('UNPUBLISHED', 'Unpublished'), ('ARCHIVED', 'Archived')], default='PUBLISHED', max_length=32),
        ),
        migrations.AlterField(
            model_name='module',
            name='source_type',
            field=models.CharField(choices=[('FXEC_OFFICIAL', 'FXEC Official Website / Document'), ('FACULTY_CREATED', 'Faculty Created'), ('ADMIN_CREATED', 'Authorized Mentor / Admin Input'), ('AI_SUGGESTED', 'AI Suggested'), ('EXTERNAL_REFERENCE', 'External Public Reference'), ('NPTEL_OFFICIAL', 'NPTEL Official Public Resource'), ('EXTERNAL_PUBLIC', 'External Public Learning Reference')], default='FXEC_OFFICIAL', max_length=32),
        ),
        migrations.AlterField(
            model_name='skill',
            name='content_status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('PENDING_ADMIN_INPUT', 'Pending Institutional Verification'), ('PUBLISHED', 'Published & Verified'), ('UNPUBLISHED', 'Unpublished'), ('ARCHIVED', 'Archived')], default='PUBLISHED', max_length=32),
        ),
        migrations.AlterField(
            model_name='skill',
            name='level',
            field=models.CharField(choices=[('BEGINNER', 'Beginner'), ('INTERMEDIATE', 'Intermediate'), ('ADVANCED', 'Advanced'), ('EXPERT', 'Expert')], default='BEGINNER', max_length=16),
        ),
        migrations.AlterField(
            model_name='skill',
            name='source_type',
            field=models.CharField(choices=[('FXEC_OFFICIAL', 'FXEC Official Website / Document'), ('FACULTY_CREATED', 'Faculty Created'), ('ADMIN_CREATED', 'Authorized Mentor / Admin Input'), ('AI_SUGGESTED', 'AI Suggested'), ('EXTERNAL_REFERENCE', 'External Public Reference'), ('NPTEL_OFFICIAL', 'NPTEL Official Public Resource'), ('EXTERNAL_PUBLIC', 'External Public Learning Reference')], default='FXEC_OFFICIAL', max_length=32),
        ),
        migrations.AlterField(
            model_name='skillcategory',
            name='content_status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('PENDING_ADMIN_INPUT', 'Pending Institutional Verification'), ('PUBLISHED', 'Published & Verified'), ('UNPUBLISHED', 'Unpublished'), ('ARCHIVED', 'Archived')], default='PUBLISHED', max_length=32),
        ),
        migrations.AlterField(
            model_name='skillcategory',
            name='source_type',
            field=models.CharField(choices=[('FXEC_OFFICIAL', 'FXEC Official Website / Document'), ('FACULTY_CREATED', 'Faculty Created'), ('ADMIN_CREATED', 'Authorized Mentor / Admin Input'), ('AI_SUGGESTED', 'AI Suggested'), ('EXTERNAL_REFERENCE', 'External Public Reference'), ('NPTEL_OFFICIAL', 'NPTEL Official Public Resource'), ('EXTERNAL_PUBLIC', 'External Public Learning Reference')], default='FXEC_OFFICIAL', max_length=32),
        ),
        migrations.CreateModel(
            name='AISkillSuggestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('category_name', models.CharField(max_length=128)),
                ('domain_name', models.CharField(blank=True, max_length=128)),
                ('level', models.CharField(choices=[('BEGINNER', 'Beginner'), ('INTERMEDIATE', 'Intermediate'), ('ADVANCED', 'Advanced'), ('EXPERT', 'Expert')], default='BEGINNER', max_length=16)),
                ('skill_type', models.CharField(choices=[('CORE', 'Core Skill'), ('ELECTIVE', 'Elective Skill'), ('FACULTY_INITIATIVE', 'Faculty Initiative'), ('EMERGING', 'Emerging / Future Skill'), ('PLACEMENT', 'Placement Fit Training'), ('TECHNICAL', 'Technical Skill'), ('NON_TECHNICAL', 'Non-Technical Skill')], default='EMERGING', max_length=32)),
                ('justification', models.TextField()),
                ('prerequisites', models.JSONField(blank=True, default=list)),
                ('suggested_modules', models.JSONField(blank=True, default=list)),
                ('learning_outcomes', models.JSONField(blank=True, default=list)),
                ('source_type', models.CharField(default='AI_SUGGESTED', max_length=32)),
                ('approval_status', models.CharField(choices=[('DRAFT', 'Draft'), ('PENDING_REVIEW', 'Pending Review'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('ARCHIVED', 'Archived')], default='PENDING_REVIEW', max_length=32)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalogue.department')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_ai_suggestions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CourseApproval',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('SUBMITTED', 'Submitted for Review'), ('APPROVED', 'Approved & Published'), ('REJECTED', 'Rejected'), ('CHANGES_REQUESTED', 'Changes Requested')], max_length=32)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approvals', to='catalogue.course')),
                ('reviewer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CourseRecommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.TextField()),
                ('score', models.FloatField(default=0.0)),
                ('recommended_sequence', models.PositiveIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalogue.course')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_recommendations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['student', 'recommended_sequence'],
            },
        ),
        migrations.CreateModel(
            name='SkillDomain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_type', models.CharField(choices=[('FXEC_OFFICIAL', 'FXEC Official Website / Document'), ('FACULTY_CREATED', 'Faculty Created'), ('ADMIN_CREATED', 'Authorized Mentor / Admin Input'), ('AI_SUGGESTED', 'AI Suggested'), ('EXTERNAL_REFERENCE', 'External Public Reference'), ('NPTEL_OFFICIAL', 'NPTEL Official Public Resource'), ('EXTERNAL_PUBLIC', 'External Public Learning Reference')], default='FXEC_OFFICIAL', max_length=32)),
                ('source_url', models.URLField(blank=True, help_text='Canonical URL where fact was retrieved', null=True)),
                ('source_title', models.CharField(blank=True, help_text='Authoritative title of webpage/document', max_length=255, null=True)),
                ('source_description', models.TextField(blank=True, help_text='Explanatory context of institutional origin', null=True)),
                ('source_accessed_at', models.DateTimeField(blank=True, help_text='Timestamp when source was accessed', null=True)),
                ('last_verified_at', models.DateTimeField(blank=True, help_text='Timestamp of last provenance verification', null=True)),
                ('approval_status', models.CharField(choices=[('DRAFT', 'Draft'), ('PENDING_REVIEW', 'Pending Review'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('ARCHIVED', 'Archived')], default='APPROVED', max_length=32)),
                ('content_status', models.CharField(choices=[('DRAFT', 'Draft'), ('PENDING_ADMIN_INPUT', 'Pending Institutional Verification'), ('PUBLISHED', 'Published & Verified'), ('UNPUBLISHED', 'Unpublished'), ('ARCHIVED', 'Archived')], default='PUBLISHED', max_length=32)),
                ('name', models.CharField(max_length=128)),
                ('description', models.TextField(blank=True)),
                ('order', models.PositiveIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_approved', to=settings.AUTH_USER_MODEL)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='domains', to='catalogue.skillcategory')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Skill Domains',
                'ordering': ['category', 'order', 'name'],
                'unique_together': {('category', 'name')},
            },
        ),
        migrations.AddField(
            model_name='skill',
            name='domain',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='skills', to='catalogue.skilldomain'),
        ),
        migrations.CreateModel(
            name='SkillRecommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.TextField()),
                ('score', models.FloatField(default=0.0)),
                ('recommended_sequence', models.PositiveIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalogue.skill')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skill_recommendations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['student', 'recommended_sequence'],
            },
        ),
        migrations.CreateModel(
            name='StudentSkillProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('selected_interests', models.JSONField(blank=True, default=list)),
                ('career_goal', models.CharField(blank=True, max_length=255)),
                ('target_role', models.CharField(blank=True, max_length=128)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='skill_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CourseVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version_number', models.PositiveIntegerField()),
                ('snapshot_data', models.JSONField(help_text='Full curriculum snapshot including modules and lessons')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('change_summary', models.TextField(blank=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='catalogue.course')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['course', '-version_number'],
                'unique_together': {('course', 'version_number')},
            },
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_type', models.CharField(choices=[('FXEC_OFFICIAL', 'FXEC Official Website / Document'), ('FACULTY_CREATED', 'Faculty Created'), ('ADMIN_CREATED', 'Authorized Mentor / Admin Input'), ('AI_SUGGESTED', 'AI Suggested'), ('EXTERNAL_REFERENCE', 'External Public Reference'), ('NPTEL_OFFICIAL', 'NPTEL Official Public Resource'), ('EXTERNAL_PUBLIC', 'External Public Learning Reference')], default='FXEC_OFFICIAL', max_length=32)),
                ('source_url', models.URLField(blank=True, help_text='Canonical URL where fact was retrieved', null=True)),
                ('source_title', models.CharField(blank=True, help_text='Authoritative title of webpage/document', max_length=255, null=True)),
                ('source_description', models.TextField(blank=True, help_text='Explanatory context of institutional origin', null=True)),
                ('source_accessed_at', models.DateTimeField(blank=True, help_text='Timestamp when source was accessed', null=True)),
                ('last_verified_at', models.DateTimeField(blank=True, help_text='Timestamp of last provenance verification', null=True)),
                ('approval_status', models.CharField(choices=[('DRAFT', 'Draft'), ('PENDING_REVIEW', 'Pending Review'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('ARCHIVED', 'Archived')], default='APPROVED', max_length=32)),
                ('content_status', models.CharField(choices=[('DRAFT', 'Draft'), ('PENDING_ADMIN_INPUT', 'Pending Institutional Verification'), ('PUBLISHED', 'Published & Verified'), ('UNPUBLISHED', 'Unpublished'), ('ARCHIVED', 'Archived')], default='PUBLISHED', max_length=32)),
                ('order', models.PositiveIntegerField(default=1)),
                ('title', models.CharField(max_length=200)),
                ('content_type', models.CharField(choices=[('VIDEO', 'Video Lecture'), ('PDF', 'PDF / Document Guide'), ('TEXT', 'Reading Material / Notes'), ('INTERACTIVE', 'Hands-on Practice / Lab Exercise')], default='TEXT', max_length=32)),
                ('content_url', models.URLField(blank=True, help_text='Lawful URL to learning resource', null=True)),
                ('text_content', models.TextField(blank=True, help_text='Curated notes, code examples, or guide')),
                ('duration_minutes', models.PositiveIntegerField(default=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_approved', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='catalogue.module')),
            ],
            options={
                'ordering': ['module', 'order'],
                'unique_together': {('module', 'order')},
            },
        ),
    ]
