# Generated by Django 5.1.15 on 2026-09-12 05:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0002_alter_skillcategory_options_course_approval_status_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('PENDING_ADMIN_INPUT', 'Pending Institutional Verification'), ('PUBLISHED', 'Published & Verified'), ('UNPUBLISHED', 'Unpublished'), ('ARCHIVED', 'Archived')], default='PUBLISHED', max_length=32),
        ),
        migrations.AddField(
            model_name='lesson',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='lesson',
            name='estimated_minutes',
            field=models.PositiveIntegerField(default=15),
        ),
        migrations.AddField(
            model_name='lesson',
            name='is_required',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='lesson',
            name='status',
            field=models.CharField(default='PUBLISHED', max_length=32),
        ),
        migrations.AddField(
            model_name='module',
            name='estimated_minutes',
            field=models.PositiveIntegerField(default=30),
        ),
        migrations.AddField(
            model_name='module',
            name='is_required',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='module',
            name='learning_objectives',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='module',
            name='status',
            field=models.CharField(default='PUBLISHED', max_length=32),
        ),
        migrations.AddField(
            model_name='skill',
            name='short_description',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='skill',
            name='slug',
            field=models.SlugField(blank=True, max_length=128, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='skill',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('PENDING_ADMIN_INPUT', 'Pending Institutional Verification'), ('PUBLISHED', 'Published & Verified'), ('UNPUBLISHED', 'Unpublished'), ('ARCHIVED', 'Archived')], default='PUBLISHED', max_length=32),
        ),
        migrations.AddField(
            model_name='skill',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.CreateModel(
            name='PracticeTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_type', models.CharField(choices=[('FXEC_OFFICIAL', 'FXEC Official Website / Document'), ('FACULTY_CREATED', 'Faculty Created'), ('ADMIN_CREATED', 'Authorized Mentor / Admin Input'), ('AI_SUGGESTED', 'AI Suggested'), ('EXTERNAL_REFERENCE', 'External Public Reference'), ('NPTEL_OFFICIAL', 'NPTEL Official Public Resource'), ('EXTERNAL_PUBLIC', 'External Public Learning Reference')], default='FXEC_OFFICIAL', max_length=32)),
                ('source_url', models.URLField(blank=True, help_text='Canonical URL where fact was retrieved', null=True)),
                ('source_title', models.CharField(blank=True, help_text='Authoritative title of webpage/document', max_length=255, null=True)),
                ('source_description', models.TextField(blank=True, help_text='Explanatory context of institutional origin', null=True)),
                ('source_accessed_at', models.DateTimeField(blank=True, help_text='Timestamp when source was accessed', null=True)),
                ('last_verified_at', models.DateTimeField(blank=True, help_text='Timestamp of last provenance verification', null=True)),
                ('approval_status', models.CharField(choices=[('DRAFT', 'Draft'), ('PENDING_REVIEW', 'Pending Review'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('ARCHIVED', 'Archived')], default='APPROVED', max_length=32)),
                ('content_status', models.CharField(choices=[('DRAFT', 'Draft'), ('PENDING_ADMIN_INPUT', 'Pending Institutional Verification'), ('PUBLISHED', 'Published & Verified'), ('UNPUBLISHED', 'Unpublished'), ('ARCHIVED', 'Archived')], default='PUBLISHED', max_length=32)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('task_type', models.CharField(choices=[('MCQ_PRACTICE', 'Concept Check MCQ Practice'), ('CODING_TASK', 'Hands-on Coding Challenge'), ('EXERCISE', 'Guided Practical Exercise'), ('ASSIGNMENT', 'Module Mini-Assignment')], default='MCQ_PRACTICE', max_length=32)),
                ('content', models.JSONField(blank=True, default=dict, help_text='Questions, starter code, test cases, or rubric')),
                ('pass_score', models.FloatField(default=70.0)),
                ('order', models.PositiveIntegerField(default=1)),
                ('is_required', models.BooleanField(default=True)),
                ('status', models.CharField(default='PUBLISHED', max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_approved', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('lesson', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='practice_tasks', to='catalogue.lesson')),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='practice_tasks', to='catalogue.module')),
            ],
            options={
                'ordering': ['module', 'order'],
            },
        ),
        migrations.CreateModel(
            name='StudyMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_type', models.CharField(choices=[('FXEC_OFFICIAL', 'FXEC Official Website / Document'), ('FACULTY_CREATED', 'Faculty Created'), ('ADMIN_CREATED', 'Authorized Mentor / Admin Input'), ('AI_SUGGESTED', 'AI Suggested'), ('EXTERNAL_REFERENCE', 'External Public Reference'), ('NPTEL_OFFICIAL', 'NPTEL Official Public Resource'), ('EXTERNAL_PUBLIC', 'External Public Learning Reference')], default='FXEC_OFFICIAL', max_length=32)),
                ('source_url', models.URLField(blank=True, help_text='Canonical URL where fact was retrieved', null=True)),
                ('source_title', models.CharField(blank=True, help_text='Authoritative title of webpage/document', max_length=255, null=True)),
                ('source_description', models.TextField(blank=True, help_text='Explanatory context of institutional origin', null=True)),
                ('source_accessed_at', models.DateTimeField(blank=True, help_text='Timestamp when source was accessed', null=True)),
                ('last_verified_at', models.DateTimeField(blank=True, help_text='Timestamp of last provenance verification', null=True)),
                ('approval_status', models.CharField(choices=[('DRAFT', 'Draft'), ('PENDING_REVIEW', 'Pending Review'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('ARCHIVED', 'Archived')], default='APPROVED', max_length=32)),
                ('content_status', models.CharField(choices=[('DRAFT', 'Draft'), ('PENDING_ADMIN_INPUT', 'Pending Institutional Verification'), ('PUBLISHED', 'Published & Verified'), ('UNPUBLISHED', 'Unpublished'), ('ARCHIVED', 'Archived')], default='PUBLISHED', max_length=32)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('resource_type', models.CharField(choices=[('PDF', 'PDF Document / Handbook'), ('DOC', 'Word Document'), ('PPT', 'Presentation Slides'), ('ARTICLE', 'Curated Technical Article'), ('NOTES', 'Instructor Lecture Notes'), ('CODE_FILE', 'Source Code File / Repository'), ('REFERENCE_LINK', 'Authoritative Web Reference'), ('PRACTICE_RESOURCE', 'Interactive Lab / Exercise Guide')], default='PDF', max_length=32)),
                ('file', models.FileField(blank=True, null=True, upload_to='materials/')),
                ('external_url', models.URLField(blank=True, null=True)),
                ('completion_method', models.CharField(choices=[('MANUAL_COMPLETE', 'Manual Complete Confirmation'), ('OPEN', 'Open Resource'), ('PAGE_PROGRESS', 'Page-by-Page Reading Verification'), ('QUIZ_AFTER_READING', 'Quiz After Reading')], default='MANUAL_COMPLETE', max_length=32)),
                ('version', models.PositiveIntegerField(default=1)),
                ('order', models.PositiveIntegerField(default=1)),
                ('is_required', models.BooleanField(default=True)),
                ('status', models.CharField(default='PUBLISHED', max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_approved', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('lesson', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='materials', to='catalogue.lesson')),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materials', to='catalogue.module')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_materials', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['module', 'order'],
            },
        ),
        migrations.CreateModel(
            name='VideoResource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_type', models.CharField(choices=[('FXEC_OFFICIAL', 'FXEC Official Website / Document'), ('FACULTY_CREATED', 'Faculty Created'), ('ADMIN_CREATED', 'Authorized Mentor / Admin Input'), ('AI_SUGGESTED', 'AI Suggested'), ('EXTERNAL_REFERENCE', 'External Public Reference'), ('NPTEL_OFFICIAL', 'NPTEL Official Public Resource'), ('EXTERNAL_PUBLIC', 'External Public Learning Reference')], default='FXEC_OFFICIAL', max_length=32)),
                ('source_url', models.URLField(blank=True, help_text='Canonical URL where fact was retrieved', null=True)),
                ('source_title', models.CharField(blank=True, help_text='Authoritative title of webpage/document', max_length=255, null=True)),
                ('source_description', models.TextField(blank=True, help_text='Explanatory context of institutional origin', null=True)),
                ('source_accessed_at', models.DateTimeField(blank=True, help_text='Timestamp when source was accessed', null=True)),
                ('last_verified_at', models.DateTimeField(blank=True, help_text='Timestamp of last provenance verification', null=True)),
                ('approval_status', models.CharField(choices=[('DRAFT', 'Draft'), ('PENDING_REVIEW', 'Pending Review'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('ARCHIVED', 'Archived')], default='APPROVED', max_length=32)),
                ('content_status', models.CharField(choices=[('DRAFT', 'Draft'), ('PENDING_ADMIN_INPUT', 'Pending Institutional Verification'), ('PUBLISHED', 'Published & Verified'), ('UNPUBLISHED', 'Unpublished'), ('ARCHIVED', 'Archived')], default='PUBLISHED', max_length=32)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('video_type', models.CharField(choices=[('UPLOADED_VIDEO', 'Uploaded Video File'), ('EXTERNAL_VIDEO', 'Approved External Educational Video')], default='EXTERNAL_VIDEO', max_length=32)),
                ('video_file', models.FileField(blank=True, null=True, upload_to='videos/')),
                ('external_url', models.URLField(blank=True, null=True)),
                ('thumbnail', models.URLField(blank=True, null=True)),
                ('duration_seconds', models.PositiveIntegerField(default=300, help_text='Total video runtime in seconds')),
                ('completion_threshold_percent', models.FloatField(default=80.0, help_text='Percentage of video that must be watched for completion')),
                ('order', models.PositiveIntegerField(default=1)),
                ('is_required', models.BooleanField(default=True)),
                ('status', models.CharField(default='PUBLISHED', max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_approved', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('lesson', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='videos', to='catalogue.lesson')),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='catalogue.module')),
            ],
            options={
                'ordering': ['module', 'order'],
            },
        ),
    ]
