# Generated by Django 5.1.15 on 2026-09-12 06:27

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0003_course_status_lesson_description_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='studymaterial',
            name='reviewed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='studymaterial',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_materials', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='studymaterial',
            name='structured_content',
            field=models.JSONField(blank=True, default=dict, help_text='Structured 9-section educational content'),
        ),
        migrations.AddField(
            model_name='studymaterial',
            name='text_content',
            field=models.TextField(blank=True, help_text='Full rendered markdown study notes'),
        ),
        migrations.AddField(
            model_name='videoresource',
            name='added_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='videoresource',
            name='added_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='added_videos', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='videoresource',
            name='channel_name',
            field=models.CharField(blank=True, help_text='Channel or author of the YouTube video', max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='videoresource',
            name='duration_if_available',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='videoresource',
            name='is_unavailable',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='videoresource',
            name='thumbnail_url',
            field=models.URLField(blank=True, help_text='Direct link to YouTube video thumbnail', null=True),
        ),
        migrations.AddField(
            model_name='videoresource',
            name='unavailable_reported_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='videoresource',
            name='verified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='videoresource',
            name='youtube_url',
            field=models.URLField(blank=True, help_text='Canonical YouTube video URL', null=True),
        ),
        migrations.AddField(
            model_name='videoresource',
            name='youtube_video_id',
            field=models.CharField(blank=True, db_index=True, help_text='Extracted 11-char YouTube ID', max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='source_type',
            field=models.CharField(choices=[('FXEC_OFFICIAL', 'FXEC Official Website / Document'), ('FACULTY_CREATED', 'Faculty Created'), ('ADMIN_CREATED', 'Authorized Mentor / Admin Input'), ('AI_SUGGESTED', 'AI Suggested'), ('AI_GENERATED', 'AI Generated'), ('YOUTUBE', 'YouTube Educational Video'), ('EXTERNAL_REFERENCE', 'External Public Reference'), ('NPTEL_OFFICIAL', 'NPTEL Official Public Resource'), ('EXTERNAL_PUBLIC', 'External Public Learning Reference')], default='FXEC_OFFICIAL', max_length=32),
        ),
        migrations.AlterField(
            model_name='department',
            name='source_type',
            field=models.CharField(choices=[('FXEC_OFFICIAL', 'FXEC Official Website / Document'), ('FACULTY_CREATED', 'Faculty Created'), ('ADMIN_CREATED', 'Authorized Mentor / Admin Input'), ('AI_SUGGESTED', 'AI Suggested'), ('AI_GENERATED', 'AI Generated'), ('YOUTUBE', 'YouTube Educational Video'), ('EXTERNAL_REFERENCE', 'External Public Reference'), ('NPTEL_OFFICIAL', 'NPTEL Official Public Resource'), ('EXTERNAL_PUBLIC', 'External Public Learning Reference')], default='FXEC_OFFICIAL', max_length=32),
        ),
        migrations.AlterField(
            model_name='learningresource',
            name='source_type',
            field=models.CharField(choices=[('FXEC_OFFICIAL', 'FXEC Official Website / Document'), ('FACULTY_CREATED', 'Faculty Created'), ('ADMIN_CREATED', 'Authorized Mentor / Admin Input'), ('AI_SUGGESTED', 'AI Suggested'), ('AI_GENERATED', 'AI Generated'), ('YOUTUBE', 'YouTube Educational Video'), ('EXTERNAL_REFERENCE', 'External Public Reference'), ('NPTEL_OFFICIAL', 'NPTEL Official Public Resource'), ('EXTERNAL_PUBLIC', 'External Public Learning Reference')], default='FXEC_OFFICIAL', max_length=32),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='source_type',
            field=models.CharField(choices=[('FXEC_OFFICIAL', 'FXEC Official Website / Document'), ('FACULTY_CREATED', 'Faculty Created'), ('ADMIN_CREATED', 'Authorized Mentor / Admin Input'), ('AI_SUGGESTED', 'AI Suggested'), ('AI_GENERATED', 'AI Generated'), ('YOUTUBE', 'YouTube Educational Video'), ('EXTERNAL_REFERENCE', 'External Public Reference'), ('NPTEL_OFFICIAL', 'NPTEL Official Public Resource'), ('EXTERNAL_PUBLIC', 'External Public Learning Reference')], default='FXEC_OFFICIAL', max_length=32),
        ),
        migrations.AlterField(
            model_name='module',
            name='source_type',
            field=models.CharField(choices=[('FXEC_OFFICIAL', 'FXEC Official Website / Document'), ('FACULTY_CREATED', 'Faculty Created'), ('ADMIN_CREATED', 'Authorized Mentor / Admin Input'), ('AI_SUGGESTED', 'AI Suggested'), ('AI_GENERATED', 'AI Generated'), ('YOUTUBE', 'YouTube Educational Video'), ('EXTERNAL_REFERENCE', 'External Public Reference'), ('NPTEL_OFFICIAL', 'NPTEL Official Public Resource'), ('EXTERNAL_PUBLIC', 'External Public Learning Reference')], default='FXEC_OFFICIAL', max_length=32),
        ),
        migrations.AlterField(
            model_name='practicetask',
            name='source_type',
            field=models.CharField(choices=[('FXEC_OFFICIAL', 'FXEC Official Website / Document'), ('FACULTY_CREATED', 'Faculty Created'), ('ADMIN_CREATED', 'Authorized Mentor / Admin Input'), ('AI_SUGGESTED', 'AI Suggested'), ('AI_GENERATED', 'AI Generated'), ('YOUTUBE', 'YouTube Educational Video'), ('EXTERNAL_REFERENCE', 'External Public Reference'), ('NPTEL_OFFICIAL', 'NPTEL Official Public Resource'), ('EXTERNAL_PUBLIC', 'External Public Learning Reference')], default='FXEC_OFFICIAL', max_length=32),
        ),
        migrations.AlterField(
            model_name='skill',
            name='source_type',
            field=models.CharField(choices=[('FXEC_OFFICIAL', 'FXEC Official Website / Document'), ('FACULTY_CREATED', 'Faculty Created'), ('ADMIN_CREATED', 'Authorized Mentor / Admin Input'), ('AI_SUGGESTED', 'AI Suggested'), ('AI_GENERATED', 'AI Generated'), ('YOUTUBE', 'YouTube Educational Video'), ('EXTERNAL_REFERENCE', 'External Public Reference'), ('NPTEL_OFFICIAL', 'NPTEL Official Public Resource'), ('EXTERNAL_PUBLIC', 'External Public Learning Reference')], default='FXEC_OFFICIAL', max_length=32),
        ),
        migrations.AlterField(
            model_name='skillcategory',
            name='source_type',
            field=models.CharField(choices=[('FXEC_OFFICIAL', 'FXEC Official Website / Document'), ('FACULTY_CREATED', 'Faculty Created'), ('ADMIN_CREATED', 'Authorized Mentor / Admin Input'), ('AI_SUGGESTED', 'AI Suggested'), ('AI_GENERATED', 'AI Generated'), ('YOUTUBE', 'YouTube Educational Video'), ('EXTERNAL_REFERENCE', 'External Public Reference'), ('NPTEL_OFFICIAL', 'NPTEL Official Public Resource'), ('EXTERNAL_PUBLIC', 'External Public Learning Reference')], default='FXEC_OFFICIAL', max_length=32),
        ),
        migrations.AlterField(
            model_name='skilldomain',
            name='source_type',
            field=models.CharField(choices=[('FXEC_OFFICIAL', 'FXEC Official Website / Document'), ('FACULTY_CREATED', 'Faculty Created'), ('ADMIN_CREATED', 'Authorized Mentor / Admin Input'), ('AI_SUGGESTED', 'AI Suggested'), ('AI_GENERATED', 'AI Generated'), ('YOUTUBE', 'YouTube Educational Video'), ('EXTERNAL_REFERENCE', 'External Public Reference'), ('NPTEL_OFFICIAL', 'NPTEL Official Public Resource'), ('EXTERNAL_PUBLIC', 'External Public Learning Reference')], default='FXEC_OFFICIAL', max_length=32),
        ),
        migrations.AlterField(
            model_name='studymaterial',
            name='resource_type',
            field=models.CharField(choices=[('AI_STUDY_NOTES', 'AI-Generated Structured Study Guide'), ('PDF', 'PDF Document / Handbook'), ('DOC', 'Word Document'), ('PPT', 'Presentation Slides'), ('ARTICLE', 'Curated Technical Article'), ('NOTES', 'Instructor Lecture Notes'), ('CODE_FILE', 'Source Code File / Repository'), ('REFERENCE_LINK', 'Authoritative Web Reference'), ('PRACTICE_RESOURCE', 'Interactive Lab / Exercise Guide')], default='AI_STUDY_NOTES', max_length=32),
        ),
        migrations.AlterField(
            model_name='studymaterial',
            name='source_type',
            field=models.CharField(choices=[('FXEC_OFFICIAL', 'FXEC Official Website / Document'), ('FACULTY_CREATED', 'Faculty Created'), ('ADMIN_CREATED', 'Authorized Mentor / Admin Input'), ('AI_SUGGESTED', 'AI Suggested'), ('AI_GENERATED', 'AI Generated'), ('YOUTUBE', 'YouTube Educational Video'), ('EXTERNAL_REFERENCE', 'External Public Reference'), ('NPTEL_OFFICIAL', 'NPTEL Official Public Resource'), ('EXTERNAL_PUBLIC', 'External Public Learning Reference')], default='FXEC_OFFICIAL', max_length=32),
        ),
        migrations.AlterField(
            model_name='videoresource',
            name='source_type',
            field=models.CharField(choices=[('FXEC_OFFICIAL', 'FXEC Official Website / Document'), ('FACULTY_CREATED', 'Faculty Created'), ('ADMIN_CREATED', 'Authorized Mentor / Admin Input'), ('AI_SUGGESTED', 'AI Suggested'), ('AI_GENERATED', 'AI Generated'), ('YOUTUBE', 'YouTube Educational Video'), ('EXTERNAL_REFERENCE', 'External Public Reference'), ('NPTEL_OFFICIAL', 'NPTEL Official Public Resource'), ('EXTERNAL_PUBLIC', 'External Public Learning Reference')], default='FXEC_OFFICIAL', max_length=32),
        ),
        migrations.AlterField(
            model_name='videoresource',
            name='video_type',
            field=models.CharField(choices=[('YOUTUBE', 'YouTube Learning Video'), ('EXTERNAL_VIDEO', 'Approved External Educational Video'), ('UPLOADED_VIDEO', 'Uploaded Video File')], default='YOUTUBE', max_length=32),
        ),
    ]
