# Generated by Django 5.1.15 on 2026-09-12 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0004_studymaterial_reviewed_at_studymaterial_reviewed_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='blueprint',
            field=models.JSONField(blank=True, default=dict, help_text='Assessment and curriculum blueprint specification'),
        ),
        migrations.AddField(
            model_name='course',
            name='learning_goal',
            field=models.TextField(blank=True, help_text='Primary engineering/career learning goal'),
        ),
        migrations.AddField(
            model_name='course',
            name='prerequisites_text',
            field=models.TextField(blank=True, help_text='AI or faculty defined textual prerequisites'),
        ),
        migrations.AddField(
            model_name='course',
            name='target_audience',
            field=models.CharField(blank=True, help_text='Target audience for course', max_length=255),
        ),
        migrations.AddField(
            model_name='lesson',
            name='common_mistakes',
            field=models.JSONField(blank=True, default=list, help_text='Typical beginner pitfalls and resolutions'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='concept_explanation',
            field=models.TextField(blank=True, help_text='Detailed conceptual exposition'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='examples',
            field=models.JSONField(blank=True, default=list, help_text='Illustrative code snippets or practical examples'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='key_points',
            field=models.JSONField(blank=True, default=list, help_text='Core takeaways to remember'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='learning_objectives',
            field=models.JSONField(blank=True, default=list, help_text='Specific learning outcomes for this lesson'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='practice_recommendation',
            field=models.TextField(blank=True, help_text='Recommended practice exercise or problem'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='summary',
            field=models.TextField(blank=True, help_text='Concise end-of-lesson wrap-up'),
        ),
        migrations.AddField(
            model_name='practicetask',
            name='difficulty',
            field=models.CharField(choices=[('EASY', 'Easy'), ('MEDIUM', 'Medium'), ('HARD', 'Hard')], default='MEDIUM', max_length=16),
        ),
        migrations.AddField(
            model_name='practicetask',
            name='explanation',
            field=models.TextField(blank=True, help_text='Pedagogical explanation shown post-submission'),
        ),
        migrations.AddField(
            model_name='studymaterial',
            name='explanation_level',
            field=models.CharField(choices=[('BEGINNER', 'Beginner Explanation'), ('INTERMEDIATE', 'Intermediate Explanation'), ('QUICK_REVISION', 'Quick Revision Notes'), ('ADVANCED', 'Advanced In-Depth Notes')], default='BEGINNER', max_length=32),
        ),
        migrations.AddField(
            model_name='studymaterial',
            name='model_provider',
            field=models.CharField(default='FXEC AI Engine (Gemini 2.5)', max_length=64),
        ),
        migrations.AddField(
            model_name='studymaterial',
            name='review_status',
            field=models.CharField(choices=[('PENDING_FACULTY_REVIEW', 'Pending Faculty Review'), ('APPROVED', 'Approved by Faculty'), ('REVISED', 'Revised by Faculty')], default='APPROVED', max_length=32),
        ),
        migrations.AddField(
            model_name='videoresource',
            name='ai_video_status',
            field=models.CharField(choices=[('NONE', 'Not Applicable'), ('SCRIPT_READY', 'AI Script & Storyboard Ready'), ('GENERATING', 'AI Video Rendering In Progress'), ('COMPLETED', 'AI Video Generated & Playable'), ('FAILED', 'AI Video Generation Failed')], default='NONE', max_length=32),
        ),
        migrations.AddField(
            model_name='videoresource',
            name='captions',
            field=models.TextField(blank=True, help_text='Subtitle or caption text in WebVTT / SRT / plain text format', null=True),
        ),
        migrations.AddField(
            model_name='videoresource',
            name='generation_id',
            field=models.CharField(blank=True, help_text='Provider task or render ID', max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='videoresource',
            name='script_package',
            field=models.JSONField(blank=True, default=dict, help_text='Structured script, narration, storyboard scenes, visual cues'),
        ),
        migrations.AddField(
            model_name='videoresource',
            name='video_provider',
            field=models.CharField(blank=True, help_text='e.g. GEMINI_OMNI, RUNWAY, HEYGEN, NONE', max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='practicetask',
            name='task_type',
            field=models.CharField(choices=[('MCQ_PRACTICE', 'Concept Check MCQ Practice'), ('CODING_TASK', 'Hands-on Coding Challenge'), ('DEBUGGING', 'Code Debugging & Fixing Challenge'), ('SHORT_ANSWER', 'Conceptual Short Answer Question'), ('FILL_BLANKS', 'Fill-in-the-Blanks Syntax Challenge'), ('PROBLEM_SOLVING', 'Algorithmic / Architectural Problem Solving'), ('EXERCISE', 'Guided Practical Exercise'), ('ASSIGNMENT', 'Module Mini-Assignment')], default='MCQ_PRACTICE', max_length=32),
        ),
        migrations.AlterField(
            model_name='studymaterial',
            name='structured_content',
            field=models.JSONField(blank=True, default=dict, help_text='Structured 9-11 section educational content'),
        ),
        migrations.AlterField(
            model_name='videoresource',
            name='video_type',
            field=models.CharField(choices=[('YOUTUBE', 'YouTube Learning Video'), ('EXTERNAL_VIDEO', 'Approved External Educational Video'), ('UPLOADED_VIDEO', 'Uploaded Video File'), ('AI_GENERATED_VIDEO', 'AI Generated Playable Video'), ('AI_VIDEO_SCRIPT', 'AI Video Script & Storyboard Package')], default='YOUTUBE', max_length=32),
        ),
    ]
