# Generated by Django 5.1.15 on 2026-09-16 05:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0005_course_blueprint_course_learning_goal_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='courses', to='catalogue.skillcategory'),
        ),
        migrations.AddField(
            model_name='course',
            name='learning_objectives',
            field=models.JSONField(blank=True, default=list, help_text='Course-level learning objectives'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='requires_notes',
            field=models.BooleanField(default=False, help_text='Lesson requires reading notes'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='requires_practice',
            field=models.BooleanField(default=False, help_text='Lesson requires completing practice'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='requires_video',
            field=models.BooleanField(default=False, help_text='Lesson requires watching attached video'),
        ),
    ]
