# Generated by Django 5.1.15 on 2026-09-18 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0006_course_category_course_learning_objectives_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='programming_language',
            field=models.CharField(blank=True, choices=[('c', 'C'), ('cpp', 'C++'), ('java', 'Java'), ('python', 'Python')], help_text='Primary programming language if this is a programming course (c, cpp, java, python)', max_length=16, null=True),
        ),
    ]
