from django.urls import path
from .views import (
    DepartmentListView,
    SkillCategoryListView,
    SkillDomainListView,
    SkillListView,
    CourseListView,
    CourseDetailView,
    ModuleDetailView,
    SkillDuplicateCheckView,
    FacultyCreateSkillView,
    FacultySkillDetailView,
    FacultyMySkillsView,
    FacultyMyCoursesView,
    FacultyCreateCourseView,
    FacultyUpdateCourseView,
    FacultySubmitReviewView,
    FacultyAIAssistBuilderView,
    AdminCourseProposalsListView,
    AdminApproveProposalView,
    AdminRejectProposalView,
    AdminPublishCourseView,
    AdminUnpublishCourseView,
    AdminArchiveCourseView,
    AdminCourseDeleteView,
    AdminVerifySourceView,
    AdminAISuggestionsListView,
    AdminApproveAISuggestionView,
    AdminAISuggestionDetailView,
    AISkillDiscoveryView,
    AISkillGenerateView,
    AISkillGapAnalysisView,
    YouTubeVideoParseView,
    VideoResourceCreateView,
    VideoResourceReviewView,
    AIStudyMaterialGenerateView,
    AdminReportedVideoIssuesView,
    AICourseGenerateView,
    CourseQuestionBankView,
    VideoPackageDetailView,
    AdminDepartmentListCreateView,
    AdminDepartmentDetailView,
    AdminDepartmentToggleStatusView
)
from .faculty_builder_views import (
    FacultyCourseCreateOrUpdateView,
    FacultyModuleCreateView,
    FacultyModuleDetailView,
    FacultyLessonCreateView,
    FacultyLessonDetailView,
    FacultyLessonAINotesView,
    FacultyLessonManualNotesView,
    FacultyLessonYouTubeView,
    FacultyLessonPracticeView,
    FacultyResourceDetailView,
    FacultyCourseValidateView,
    FacultyCourseSubmitReviewView,
    FacultyCoursePreviewView,
    AIYouTubeSuggestionsView,
    AIStudyMaterialPreviewView,
    AdminCourseReviewsListView,
    AdminCourseReviewActionView,
    StudentCourseDetailByIdView,
    StudentCourseProgressByIdView,
    FacultyCourseFinalAssessmentView,
    FacultyCourseAssessmentQuestionCreateOrUpdateView,
    FacultyCourseAssessmentAIGenerateView
)

urlpatterns = [
    # Student & Public Catalogue
    path('departments/', DepartmentListView.as_view(), name='department_list'),
    path('categories/', SkillCategoryListView.as_view(), name='category_list'),
    path('domains/', SkillDomainListView.as_view(), name='domain_list'),
    path('skills/', SkillListView.as_view(), name='skill_list'),
    path('courses/', CourseListView.as_view(), name='course_list'),
    path('courses/generate/', AICourseGenerateView.as_view(), name='ai_course_generate'),
    path('courses/<slug:slug>/', CourseDetailView.as_view(), name='course_detail'),
    path('modules/<int:pk>/', ModuleDetailView.as_view(), name='module_detail'),

    # YouTube Video & AI Curriculum Endpoints
    path('videos/parse/', YouTubeVideoParseView.as_view(), name='youtube_parse'),
    path('videos/create/', VideoResourceCreateView.as_view(), name='video_create'),
    path('videos/<int:pk>/review/', VideoResourceReviewView.as_view(), name='video_review'),
    path('modules/<int:pk>/generate-study-material/', AIStudyMaterialGenerateView.as_view(), name='module_generate_study_material'),

    # Faculty Endpoints
    path('faculty/skills/check-duplicate/', SkillDuplicateCheckView.as_view(), name='faculty_skill_check_duplicate'),
    path('faculty/skills/', FacultyCreateSkillView.as_view(), name='faculty_create_skill'),
    path('faculty/skills/<int:pk>/', FacultySkillDetailView.as_view(), name='faculty_skill_detail'),
    path('faculty/my-skills/', FacultyMySkillsView.as_view(), name='faculty_my_skills'),
    path('faculty/my-courses/', FacultyMyCoursesView.as_view(), name='faculty_my_courses'),
    path('faculty/courses/', FacultyCreateCourseView.as_view(), name='faculty_create_course'),
    path('faculty/courses/<int:pk>/', FacultyUpdateCourseView.as_view(), name='faculty_update_course'),
    path('faculty/courses/<int:pk>/submit-review/', FacultySubmitReviewView.as_view(), name='faculty_submit_review'),
    path('faculty/ai-assist/', FacultyAIAssistBuilderView.as_view(), name='faculty_ai_assist'),

    # Admin Governance Endpoints
    path('admin/course-proposals/', AdminCourseProposalsListView.as_view(), name='admin_course_proposals'),
    path('admin/course-proposals/<int:pk>/approve/', AdminApproveProposalView.as_view(), name='admin_approve_proposal'),
    path('admin/course-proposals/<int:pk>/reject/', AdminRejectProposalView.as_view(), name='admin_reject_proposal'),
    path('admin/course-proposals/<int:pk>/', AdminCourseDeleteView.as_view(), name='admin_delete_proposal'),
    path('admin/courses/<int:pk>/publish/', AdminPublishCourseView.as_view(), name='admin_publish_course'),
    path('admin/courses/<int:pk>/unpublish/', AdminUnpublishCourseView.as_view(), name='admin_unpublish_course'),
    path('admin/courses/<int:pk>/archive/', AdminArchiveCourseView.as_view(), name='admin_archive_course'),
    path('admin/courses/<int:pk>/delete/', AdminCourseDeleteView.as_view(), name='admin_course_delete'),
    path('admin/courses/<int:pk>/', AdminCourseDeleteView.as_view(), name='admin_course_detail'),
    path('admin/verify-source/', AdminVerifySourceView.as_view(), name='admin_verify_source'),
    path('admin/ai-suggestions/', AdminAISuggestionsListView.as_view(), name='admin_ai_suggestions'),
    path('admin/ai-suggestions/<int:pk>/', AdminAISuggestionDetailView.as_view(), name='admin_ai_suggestion_detail'),
    path('admin/ai-suggestions/<int:pk>/approve/', AdminApproveAISuggestionView.as_view(), name='admin_approve_ai_suggestion'),
    path('admin/reported-videos/', AdminReportedVideoIssuesView.as_view(), name='admin_reported_videos'),
    path('admin/reported-videos/<int:pk>/resolve/', AdminReportedVideoIssuesView.as_view(), name='admin_resolve_reported_video'),
    path('admin/reported-videos/<int:pk>/', AdminReportedVideoIssuesView.as_view(), name='admin_delete_reported_video'),
    path('admin/departments/', AdminDepartmentListCreateView.as_view(), name='admin_departments_list_create'),
    path('admin/departments/<int:pk>/', AdminDepartmentDetailView.as_view(), name='admin_department_detail'),
    path('admin/departments/<int:pk>/toggle-status/', AdminDepartmentToggleStatusView.as_view(), name='admin_department_toggle_status'),

    # AI Discovery & Recommendations
    path('ai/skill-suggestions/', AISkillDiscoveryView.as_view(), name='ai_skill_suggestions'),
    path('ai/skills/generate/', AISkillGenerateView.as_view(), name='ai_skill_generate'),
    path('ai/skill-gap-analysis/', AISkillGapAnalysisView.as_view(), name='ai_skill_gap_analysis'),

    # Full AI Course Generation & Question Bank
    path('courses/<int:course_id>/question-bank/', CourseQuestionBankView.as_view(), name='course_question_bank'),
    path('courses/<int:course_id>/question-bank/expand/', CourseQuestionBankView.as_view(), name='course_question_bank_expand'),
    path('videos/<int:video_id>/package/', VideoPackageDetailView.as_view(), name='video_package_detail'),

    # Faculty Course Builder & Resource Management
    path('faculty/courses/manage/', FacultyCourseCreateOrUpdateView.as_view(), name='faculty_courses_manage'),
    path('faculty/courses/manage/<int:pk>/', FacultyCourseCreateOrUpdateView.as_view(), name='faculty_course_manage_detail'),
    path('faculty/courses/<int:course_id>/modules/', FacultyModuleCreateView.as_view(), name='faculty_create_module'),
    path('faculty/modules/<int:pk>/', FacultyModuleDetailView.as_view(), name='faculty_module_detail'),
    path('faculty/modules/<int:module_id>/lessons/', FacultyLessonCreateView.as_view(), name='faculty_create_lesson'),
    path('faculty/lessons/<int:pk>/', FacultyLessonDetailView.as_view(), name='faculty_lesson_detail'),
    path('faculty/lessons/<int:pk>/ai-notes/', FacultyLessonAINotesView.as_view(), name='faculty_lesson_ai_notes'),
    path('faculty/lessons/<int:pk>/notes/', FacultyLessonManualNotesView.as_view(), name='faculty_lesson_notes'),
    path('faculty/lessons/<int:pk>/youtube/', FacultyLessonYouTubeView.as_view(), name='faculty_lesson_youtube'),
    path('faculty/lessons/<int:pk>/practice/', FacultyLessonPracticeView.as_view(), name='faculty_lesson_practice'),
    path('faculty/resources/<int:pk>/', FacultyResourceDetailView.as_view(), name='faculty_resource_detail'),
    path('faculty/courses/<int:pk>/validate/', FacultyCourseValidateView.as_view(), name='faculty_course_validate'),
    path('faculty/courses/<int:pk>/preview/', FacultyCoursePreviewView.as_view(), name='faculty_course_preview'),
    path('faculty/courses/<int:course_id>/final-assessment/', FacultyCourseFinalAssessmentView.as_view(), name='faculty_course_final_assessment'),
    path('faculty/courses/<int:course_id>/final-assessment/questions/', FacultyCourseAssessmentQuestionCreateOrUpdateView.as_view(), name='faculty_course_assessment_questions'),
    path('faculty/courses/<int:course_id>/final-assessment/questions/<int:question_id>/', FacultyCourseAssessmentQuestionCreateOrUpdateView.as_view(), name='faculty_course_assessment_question_detail'),
    path('faculty/courses/<int:course_id>/final-assessment/generate-ai-questions/', FacultyCourseAssessmentAIGenerateView.as_view(), name='faculty_course_assessment_ai_generate'),

    # AI Video & Study Notes Discovery
    path('ai/youtube-suggestions/', AIYouTubeSuggestionsView.as_view(), name='ai_youtube_suggestions'),
    path('ai/study-material/', AIStudyMaterialPreviewView.as_view(), name='ai_study_material_preview'),

    # Admin Course Review
    path('admin/course-reviews/', AdminCourseReviewsListView.as_view(), name='admin_course_reviews'),
    path('admin/course-reviews/<int:pk>/approve/', AdminCourseReviewActionView.as_view(), {'action': 'APPROVE'}, name='admin_course_review_approve'),
    path('admin/course-reviews/<int:pk>/reject/', AdminCourseReviewActionView.as_view(), {'action': 'REJECT'}, name='admin_course_review_reject'),

    # Student Course by ID & Progress
    path('courses/by-id/<int:pk>/', StudentCourseDetailByIdView.as_view(), name='student_course_by_id'),
    path('courses/<int:pk>/progress/', StudentCourseProgressByIdView.as_view(), name='student_course_progress_by_id'),
]
