# Generated by Django 5.1.15 on 2026-09-16 04:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificates', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CertificateConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('institution_name', models.CharField(default='FRANCIS XAVIER ENGINEERING COLLEGE', max_length=255)),
                ('subtext', models.CharField(blank=True, default='(Autonomous)', max_length=255)),
                ('accreditation_text', models.CharField(blank=True, default="Accredited by NBA & NAAC 'A' Grade • Affiliated to Anna University", max_length=255)),
                ('signatory_1_title', models.CharField(default='Authorized Signatory', max_length=128)),
                ('signatory_1_name', models.CharField(blank=True, default='', max_length=128)),
                ('signatory_2_title', models.CharField(default='Course Coordinator', max_length=128)),
                ('signatory_2_name', models.CharField(blank=True, default='', max_length=128)),
                ('cert_id_prefix', models.CharField(default='FXEC-SKILL', max_length=32)),
                ('watermark_enabled', models.BooleanField(default=True)),
                ('watermark_opacity', models.FloatField(default=0.08)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='certificate',
            name='assessment_score',
            field=models.CharField(blank=True, default='', max_length=32),
        ),
        migrations.AddField(
            model_name='certificate',
            name='skill',
            field=models.CharField(blank=True, default='', max_length=128),
        ),
        migrations.AddField(
            model_name='certificate',
            name='status',
            field=models.CharField(choices=[('VALID', 'Valid'), ('REVOKED', 'Revoked')], db_index=True, default='VALID', max_length=16),
        ),
        migrations.CreateModel(
            name='BrandingAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asset_type', models.CharField(choices=[('HORIZONTAL_LOGO', 'Horizontal Institutional Logo'), ('CIRCULAR_EMBLEM', 'Circular FXEC Emblem'), ('WATERMARK', 'Campus / Institutional Watermark')], db_index=True, max_length=32)),
                ('image', models.FileField(upload_to='branding/')),
                ('filename', models.CharField(blank=True, max_length=255)),
                ('version', models.PositiveIntegerField(default=1)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive')], db_index=True, default='ACTIVE', max_length=16)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_branding_assets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-version', '-uploaded_at'],
            },
        ),
    ]
