# Generated by Django 5.1.15 on 2026-09-18 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificates', '0002_certificateconfig_certificate_assessment_score_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificateconfig',
            name='accreditation_text',
            field=models.CharField(blank=True, default='Approved by AICTE & Affiliated to Anna University', max_length=255),
        ),
    ]
